### ISSUE TITLE
Disable SSL verify for self signed certs to a s3 server like minio

### ISSUE THREAD

**Issue by spijker** [parseablehq/parseable#284]
Please add a flag to disable the verify for self signed certs.
maybe : 
env-vars : P_S3_SSL_VERIFY_PEER
secret : s3.ssl.verify.peer: false

**Comment by nitisht** [comment]
Thanks @spijker we'll tale this up for the next release

**Comment by nitisht** [comment]
@spijker there is some context to this. We currently use two different S3 clients, but we intend to standardize on the https://github.com/apache/arrow-rs/tree/master/object_store.

However there is a small issue Ref https://github.com/apache/arrow-rs/issues/3725 that will break an existing parseable feature. We're waiting on this to get solved and then unify on object_store and then add the skip verification flag. Thank you for the patience. 

Meanwhile, would it be possible to try parseable with a MinIO cert with https://letsencrypt.org/, so that you can proceed with your testing

**Comment by spijker** [comment]
@nitisht 
Yes, I'm testing now with that option.
Thx for the update.
