### ISSUE TITLE
Add support for relative datetime in query

### ISSUE THREAD

**Issue by logut** [parseablehq/parseable#490]
To make automated queries easier, being able to specify start and end time by relative offsets would be nice.

To query the last 10min we could use something like the following code:
```json
{
	"endTime": "now",
	"query": "SELECT * FROM stream;",
	"startTime": "-10min"
}
```

**Comment by trueleo** [comment]
@logut Thank you for the suggestion. I will add this because as this is also something added to datafusion while ago. We eventually should move away from explicit time here and infer catalog from `where p_timestamp` clauses. There we can also this function use https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#now
