### ISSUE TITLE
Allow setting auth strategy to bearer instead of just basic

### ISSUE THREAD

**Issue by rjhawar** [parseablehq/parseable#560]
Currently the docs only show how to setup log ingestion using basic auth, but typically most setups use the bearer auth method instead.The bearer token value (OAuth2, JWT, etc.) is passed as-is.

Are you planning to integrate more advanced auth methods?
I feel like this is an area that needs some work especially considering log data can contain sensitive information.

relevant docs: https://www.parseable.io/docs/concepts#authentication

**Comment by trueleo** [comment]
Please refer to https://www.parseable.io/docs/oidc for openid connect configuration.

That said basic auth is secure enough with SSL enabled unless subject to a third party https proxy or something similar

**Comment by rjhawar** [comment]
@trueleo I respectfully disagree with you view here:

By your logic your better with no authentication if your relying on SSL encryption. 
Theoretically if someone breaks your SSL encryption then they automatically comprise the admin or whatever account you set.
Your better off using bearer auth in all scenarios. The bearer token has no relation to any accounts and as such is less risky to send across the web. Even in the most basic scenario where you use plain HTTP without encryption bearer auth is still more secure then basic auth.

**Comment by trueleo** [comment]
@rjhawar We understand the risks related to authentication mechanisms. Even OpenId connect token mechanism has it's own issues that's why we opted for a session mechanism on top of it. 

This is based on https://blog.duendesoftware.com/posts/20210326_bff/ 

For OpenId Connect your actual code and id-token are exchanged on the back channel i.e where Parseable server is running ( not from browser/client ). 

This means 
* On basic auth side one is relying on the ssl and infra security between Parseable and client/browser for session exchange.
* On OAuth/OpenId connect side one is relying on the SSL between client and authentication provider and then on backchannel exchange security between parseable instance and authentication provider. 


In case of any compromise we have following options in place. 
* You can reset password for basic auth user.
* You can reset all active sessions for all users at once which will prompt a re-authentication

**Comment by rjhawar** [comment]
@trueleo appreciate you taking the time out to respond so throughly.
Great work on the log tool so far!

**Comment by nitisht** [comment]
Also @rjhawar Please check out the roles - https://www.parseable.io/docs/rbac. The agent can have a `Ingester` role, so in case of a leak, you're still okay.
