### ISSUE TITLE
Server throws "User Does not have permission to access this" occasionally (arrow flight endpoint).

### ISSUE THREAD

**Issue by balaji-jr** [parseablehq/parseable#822]
[python-script.txt](https://github.com/user-attachments/files/16141168/script.txt)

requirements
`certifi==2024.2.2
charset-normalizer==3.3.2
grpcio==1.62.2
idna==3.7
numpy==1.26.4
ordered-set==4.1.0
pandas==2.2.2
py2wasm==2.6.2
pyarrow==15.0.2
python-dateutil==2.9.0.post0
pytz==2024.1
requests==2.31.0
six==1.16.0
tqdm==4.66.2
tzdata==2024.1
urllib3==2.2.1
zstandard==0.22.0
`

Steps to reproduce: 

1. Close all console instances in the browser
2. Restart the server.
3. Run the Python script (with a valid stream name and range)
4. Now open the console and login and go to any page
5. Run the same script again

Server throws: 
`pyarrow._flight.FlightUnauthorizedError: Flight returned unauthorized error, with message: User Does not have permission to access this. gRPC client debug context: UNKNOWN:Error received from peer ipv4:127.0.0.1:8002 {created_time:"2024-07-09T14:42:00.892379+05:30", grpc_status:7, grpc_message:"User Does not have permission to access this"}. Client context: IOError: Server never sent a data message. Detail: Internal`

**Comment by dharanad** [comment]
Source if error
https://github.com/parseablehq/parseable/blob/c4731e62cd4733b55d680b98995bb6c74c842c76/server/src/handlers/airplane.rs#L234

Post restart when running the py script.
`Users.get_permissions()` was returning couple of permission namely `Stream` & `SelfUser`

Once the user logs into the console.

The same function `Users.get_permissions()` returns 0 permission. Because of which `authorize_and_set_filter_tags` responds with error.

Need to investigate what happes to maps inside `Sessions` objects once the users logs in.

**Comment by nitisht** [comment]
thanks @dharanad do you want to pick this up?

**Comment by dharanad** [comment]
> thanks @dharanad do you want to pick this up?

Yes i would like to
