### ISSUE TITLE
Suggestion: log the staging file name and stream on which Parseable is panicking

### ISSUE THREAD

**Issue by krumpira** [parseablehq/parseable#834]
Hey Team. Thank you for making this great tool!

During my use of Parseable I stumbled upon a few 'panic' situations. Some of them were resolved by deleting all parquet and arrows files from the staging dir. Since that is non-optimal, it would be very useful if **stream and file name** were printed in the panic log.
I already tried with RUST_BACKTRACE=1 and RUST_BACKTRACE=full, but the stream nor file name are printed.

Example panic messages:
```
thread '<unnamed>' panicked at server/src/utils/arrow/batch_adapter.rs:47:47:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("column types must match schema types, expected Utf8 but found Null at column index 4")
```

```
thread 'main' panicked at server/src/metadata.rs:365:10:
called `Result::unwrap()` on an `Err` value: ()
```

```
thread '<unnamed>' panicked at server/src/utils/arrow/reverse_reader.rs:133:13:
range start index 1 out of range for slice of length 0
```

Kind Regards.

**Comment by nikhilsinhaparseable** [comment]
@krumpira thank you again for showing interest and using Parseable.
We are deleting the invalid parquets and arrows (of 0 size) to avoid panics, we have also added an error log in such cases.

We will add the stream name and file name getting deleted. You can find this in the next release.

We also want to understand the case where you see such issues.
Can you provide some steps to reproduce the issue for us to analyse the root cause.

Please join our slack community and help us perform the RCA.
https://join.slack.com/t/parseable/shared_invite/zt-23t505gz7-zX4T10OvkS8RAhnme4gDZQ

Thanks!
